services:
  - type: web
    name: notes-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn notes_app.notes_app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: notes_app.notes_app.settings
